### PR TITLE
Shellcheck integration

### LINKED ISSUE #35: shellcheck linting
I use [shellcheck](https://github.com/koalaman/shellcheck) myself for all of my scripts, it helps avoid common bash mistakes, I also have it integrated with Travis for my projects. @wesbarnett would you accept a PR with shellcheck changes integrated and a `.travis.yml` to have it checked?

### PR DESCRIPTION
**Pull request by kalbasit**
Example of a failing build: https://travis-ci.org/kalbasit/snap-sync/builds/237245285
Example of a working build: https://travis-ci.org/kalbasit/snap-sync/builds/237246394

@wesbarnett this would work best if you require PR and status check for the master branch.

closes #35

### CODE REVIEW

**Comment by NicoHood** [comment]
set -e is not an option. Also you have to doublecheck the corrections from shellcheck, as sometime especially quotes will cause scripts to missfunction in some situations. I think its good to check and correct the warnings, but if travis is really required only @wesbarnett can decide.

**Comment by kalbasit** [comment]
@NicoHood why do you think `set -e` is not appropriate here? You do not want the script to continue when an error happens.

**Comment by NicoHood** [comment]
Because a trap is the cleaner and safer option. @wesbarnett already implemented this now.

@wesbarnett You should include a line trace to the exiting function.

BTW: I tried to trap errors inside a function without success. Do you know why? Sample:
https://gist.github.com/NicoHood/642b4d426f54fd050bddbb88eb81d855

**Comment by kalbasit** [comment]
From https://stackoverflow.com/questions/35800082/bash-how-to-trap-err-when-using-set-e
```
You need to use set -o errtrace for the function to inherit the trap.
```

so you essentially need `set -eE` alongside the trap ERR

**Comment by wesbarnett** [comment]
See #39 where I added line tracing. `set -o errtrace` is needed but `set -e` is not.

**Comment by kalbasit** [comment]
@wesbarnett `set -E` (or `set -o errtrace`) is needed, that's correct. I usually add `set -e` as a failsafe but I'm not sure if it would help here. I'll update my PR to keep yours.

**Comment by wesbarnett** [comment]
Although some of these shellcheck recommendations are useful, it gets a little overzealous with things. For now I'll prefer not to implement all of them since the script is working correctly. Thanks.

**Pull request closed without merging**
