### PR TITLE
Wip dash v2

### PR DESCRIPTION
**Pull request by rzerres**
Hey WES,

i have rebased on top of your latest commit 0875b5e.
i also included the progname typo "mismatch" and an explicit subvolid (--SUBVOLID | ---subvolid | -s

cheers
Ralf

PS: of corse I'm open for further discussion
PPS: i'd like to incorporate a possibility to use snapper on target side. This needs further testing. It might be possible to include a snapper template for snap-sync (e.g via config-templates=snap-sync) which will only present the needed options.
The given function verfiy_snapper_function () could call a create_target_snapper_structure () and call snapper --config $selected_config create --config-template snap-sync to create the .snapshot etc.
So I don't have investigated, wether the btrfs-send snapshot structure will make it as expeted. But the vision is a target hosted basis handle the disk -> tape part that i haven't worked on jet .....

### CODE REVIEW

**Comment by rzerres** [comment]
Update: 
i successfully tested the possibility to manage snap-sync backups on a remote server via snapper. An initial implementation is in WIP-dash2 (72cf74ffb8334d57863913431d7850897c2c24f2), that you can cherry-pick.

cheers
Ralf

**Comment by rzerres** [comment]
update:
got a working milestone supporting snapper functionality for target snapshots. Updated the README.
I did test on my local machine, as well as syncing to a ssh accessible remote host. It seems that exceptions are reported as expected. 
I also tested to sync same source target to different target disks. All works fine.
Feel free to ask if anything has glidges ....

Ralf

PS: I have seen, that you have 0.5 as a next milestone. Any expected release date?

**Comment by rzerres** [comment]
Hey WES,

again, i rebased on you lastest commit (6bcc54b).
Since my last comment, quite a lot has happend. I cleaned up the commits, to reflact the major changes.

I tested to sync following szenarios:
- sync to local attached subvolume (first: full sync; upgrades: incremental sync)
- sync to remote attached subvolume (first: full sync: upgrades: incremental sync)

since the distinction within snapper is based on the combination of subvolid and uuid, the source snapper config is happy to server backups to multiple destinct target subvolumes.

I do like the possibility to change the backupdir, even if you have synced before (--interactive). All synced backups to the former destination in targets subvolume are kept as is (inclusive the snapper target structure). The snapper target config is adapted to reflect the new subvolume location. All pathes are recreated as needed. Once the sync has finished, management of the target config keeps identical. You can even switch back to an old backupdir.

For bigger syncs (mainly for initial calls), the visualization via pv comes in handy. I'm using output redirection of btrfs-send and btrfs-receive calls (stderror: takes the actual brtrfs messages). The retrun code is tracked. Any error will be advertised as a return-code > 0. That is all i need. The stderror is piped to a fifo. Thus it can be presented, if the pipe fails for further investigation.

All features are working for me. That doesn't mean that there isn't potential to improve. I didn't got a nice straightforward handling to advertise snapper to reread it's structure explicitely. Have asked for help  (#https://github.com/openSUSE/snapper/issues#372). Hopefully there will be a better solution. Right now the code has an ugly hack to wait until snapper keeps up. This is needed, to tag destination snapshot userdata. It will keep the reverse path to the source (host, subvolid, uuid).

Cheers,
Ralf

PS: Maybe you are busy. Maybe you dislike the code or implementation decisions.  I would love to get some feedback. ...

**Comment by wesbarnett** [comment]
I haven't had much time to thoroughly look through everything. Honestly this program begin just as a simple way for me to back up my own snapshots, and I really can't go through your modifications with the amount of detail it deserves. I want to offer the suggestion that perhaps your rewrite can continue as its own project? I like the concepts you've implemented, but don't think I will merge them into this project since that gives the impression that I have reviewed the code, and it's too much for me to go over. Thoughts?

**Comment by NicoHood** [comment]
I personally did not yet look into the new code, but the features definitely sounds worth reviewing. I totally understand that @wesbarnett aint got time, but some day he possibly will. Or someone else, maybe me too, will do a review.

As an alternative you can try to push new features as separate PRs in smaller chunks. I'd just give it more time.

**Comment by rzerres** [comment]
@wesbarnett,
@NicoHood,

i dislike the idea on a standalone projekt. The idea and basic work was done by Wes. It got me going, I did watch up  https://btrfs.wiki.kernel.org/index.php/Incremental_Backup with all the stuff others already came up with. Some of this projects are quite mature and feature complete.
None really took up the idea to rely on snapper. From my perspective, if relying on btrfs, snapper is a natural complement. Being able to replicate and combine the strenght of both projects are a very fruitfull path.

Because i need to get a solution on customer side, which will take care of multiple subvolumes and huge date-sizes (>10TB), I gave snap-sync a try. First i started as an experiment. Then it turned out to solve the 'flat-file' backup idea. Take a disk, use a cron and keep a history. Right, it took much more effort then I did estimate when i started. But the result is productive for me, in this specific case.

We might check it in as a sub-branch on this site to keep it together. And because of the fact, that the rework is done as posix shell, i doutht it makes sense to cherry-pick parts and port it back to the bash way. Of corse you can do, but you can run the port form bash ....
There are 2 minor corners, i might clean up as a last step to a final release. I don't have a personal reputation issue, so it can stay as is, or get some others to review, if they have time.

Ralf

**Comment by wesbarnett** [comment]
@rzerres I want to reiterate that I am not able to review your code, so I'm not going to be able to merge this pull request. I am going to link to your version for those who are interested.

**Comment by rzerres** [comment]
Hey Wes,

thats OK for me. I might rename my wip branche to be the master. Thus we will have two projects. And that wasen't my gole.
Still have a feature request at snapper developer to get rid oft a hack inside snap-sync. My actual tree has the same features as your master branche, plus the mentioned snapper structure. This feature helps me a lot at customer side, where i do backup a couple Terabyte of storage in to backup Servers raids.

Best regards
Ralf

Am 20.01.2018 17:13 schrieb James “Wes” Barnett <notifications@github.com>:

@rzerres<https://github.com/rzerres> I want to reiterate that I am not able to review your code, so I'm not going to be able to merge this pull request. I am going to link to your version for those who are interested.

**Pull request closed without merging**
